algoritmo "Ex-16"
var
//padrão camel case e deixar os nomes mais descritivos: qtdCigarrosDia, tempoAno
CigarrosD, TempoA: inteiro
TempoP, Total:real
inicio

 Escreval("Quantos cigarros vocÍ fuma por dia ?" )
 Leia (CigarrosD)
 //espaço
 Escreval("A quantos anos vocÍ jŠ fuma ?")
 Leia(TempoA)
 //espaço
 TempoP<- CigarrosD * 2,4
 Total<- TempoA * TempoP
 Escreval("O total de dias que vocÍ perderŠ ť : " , Total )

fimalgoritmo